/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface InteractiveOptimisticRollupInterface extends Interface {
    getFunction(nameOrSignature: "batches" | "bisectDispute" | "challengePeriod" | "challengerBond" | "claimableBalances" | "disputes" | "finalizeBatch" | "getBatchDeltas" | "getDeltaAt" | "initiateChallenge" | "latestBatchId" | "resolveSingleStep" | "sequencerBond" | "submitBatch" | "submitChallengerMidpointClaim" | "submitChallengerSingleStepClaim" | "submitSequencerMidpointClaim" | "submitSequencerSingleStepClaim" | "withdrawClaimable"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BatchFinalized" | "BatchSubmitted" | "ChallengeInitiated" | "DisputeBisected" | "DisputeResolved" | "MidpointClaimSubmitted" | "SingleStepClaimSubmitted"): EventFragment;

    encodeFunctionData(functionFragment: 'batches', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'bisectDispute', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'challengePeriod', values?: undefined): string;
encodeFunctionData(functionFragment: 'challengerBond', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimableBalances', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'disputes', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'finalizeBatch', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getBatchDeltas', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getDeltaAt', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'initiateChallenge', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'latestBatchId', values?: undefined): string;
encodeFunctionData(functionFragment: 'resolveSingleStep', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'sequencerBond', values?: undefined): string;
encodeFunctionData(functionFragment: 'submitBatch', values: [BigNumberish, BigNumberish, BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'submitChallengerMidpointClaim', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'submitChallengerSingleStepClaim', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'submitSequencerMidpointClaim', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'submitSequencerSingleStepClaim', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawClaimable', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'batches', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bisectDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'challengePeriod', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'challengerBond', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimableBalances', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'disputes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalizeBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBatchDeltas', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDeltaAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initiateChallenge', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'latestBatchId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveSingleStep', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sequencerBond', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitChallengerMidpointClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitChallengerSingleStepClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitSequencerMidpointClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitSequencerSingleStepClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawClaimable', data: BytesLike): Result;
  }

  
    export namespace BatchFinalizedEvent {
      export type InputTuple = [batchId: BigNumberish, claimedFinalState: BigNumberish];
      export type OutputTuple = [batchId: bigint, claimedFinalState: bigint];
      export interface OutputObject {batchId: bigint, claimedFinalState: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BatchSubmittedEvent {
      export type InputTuple = [batchId: BigNumberish, initialState: BigNumberish, claimedFinalState: BigNumberish, txCount: BigNumberish, submittedAt: BigNumberish];
      export type OutputTuple = [batchId: bigint, initialState: bigint, claimedFinalState: bigint, txCount: bigint, submittedAt: bigint];
      export interface OutputObject {batchId: bigint, initialState: bigint, claimedFinalState: bigint, txCount: bigint, submittedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ChallengeInitiatedEvent {
      export type InputTuple = [batchId: BigNumberish, challengerFinalState: BigNumberish];
      export type OutputTuple = [batchId: bigint, challengerFinalState: bigint];
      export interface OutputObject {batchId: bigint, challengerFinalState: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputeBisectedEvent {
      export type InputTuple = [batchId: BigNumberish, start: BigNumberish, end: BigNumberish, mid: BigNumberish, lowerHalfDisputed: boolean];
      export type OutputTuple = [batchId: bigint, start: bigint, end: bigint, mid: bigint, lowerHalfDisputed: boolean];
      export interface OutputObject {batchId: bigint, start: bigint, end: bigint, mid: bigint, lowerHalfDisputed: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputeResolvedEvent {
      export type InputTuple = [batchId: BigNumberish, challengerWon: boolean, sequencerWon: boolean, disputedIndex: BigNumberish];
      export type OutputTuple = [batchId: bigint, challengerWon: boolean, sequencerWon: boolean, disputedIndex: bigint];
      export interface OutputObject {batchId: bigint, challengerWon: boolean, sequencerWon: boolean, disputedIndex: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MidpointClaimSubmittedEvent {
      export type InputTuple = [batchId: BigNumberish, claimer: AddressLike, isSequencer: boolean, mid: BigNumberish, claimedStateAtMid: BigNumberish];
      export type OutputTuple = [batchId: bigint, claimer: string, isSequencer: boolean, mid: bigint, claimedStateAtMid: bigint];
      export interface OutputObject {batchId: bigint, claimer: string, isSequencer: boolean, mid: bigint, claimedStateAtMid: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SingleStepClaimSubmittedEvent {
      export type InputTuple = [batchId: BigNumberish, claimer: AddressLike, isSequencer: boolean, disputedIndex: BigNumberish, claimedPostState: BigNumberish];
      export type OutputTuple = [batchId: bigint, claimer: string, isSequencer: boolean, disputedIndex: bigint, claimedPostState: bigint];
      export interface OutputObject {batchId: bigint, claimer: string, isSequencer: boolean, disputedIndex: bigint, claimedPostState: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface InteractiveOptimisticRollup extends BaseContract {
    
    connect(runner?: ContractRunner | null): InteractiveOptimisticRollup;
    waitForDeployment(): Promise<this>;

    interface: InteractiveOptimisticRollupInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    batches: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, bigint, bigint, boolean, boolean, boolean, boolean] & {sequencer: string, initialState: bigint, claimedFinalState: bigint, submittedAt: bigint, txCount: bigint, challenged: boolean, finalized: boolean, invalidated: boolean, bondSettled: boolean }],
      'view'
    >
    

    
    bisectDispute: TypedContractMethod<
      [_batchId: BigNumberish, _sequencerStateAtMid: BigNumberish, _challengerStateAtMid: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    challengePeriod: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    challengerBond: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    claimableBalances: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    disputes: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, boolean, boolean, bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean, boolean, bigint, bigint, boolean, boolean, boolean, boolean] & {challenger: string, active: boolean, resolved: boolean, start: bigint, end: bigint, mid: bigint, sequencerFinalState: bigint, challengerFinalState: bigint, sequencerStateAtMid: bigint, challengerStateAtMid: bigint, sequencerMidSubmitted: boolean, challengerMidSubmitted: boolean, sequencerSingleStepPostState: bigint, challengerSingleStepPostState: bigint, sequencerSingleStepSubmitted: boolean, challengerSingleStepSubmitted: boolean, sequencerWon: boolean, challengerWon: boolean }],
      'view'
    >
    

    
    finalizeBatch: TypedContractMethod<
      [_batchId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getBatchDeltas: TypedContractMethod<
      [_batchId: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    getDeltaAt: TypedContractMethod<
      [_batchId: BigNumberish, _index: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    initiateChallenge: TypedContractMethod<
      [_batchId: BigNumberish, _challengerFinalState: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    latestBatchId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    resolveSingleStep: TypedContractMethod<
      [_batchId: BigNumberish, _sequencerClaimedPostState: BigNumberish, _challengerClaimedPostState: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    sequencerBond: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    submitBatch: TypedContractMethod<
      [_initialState: BigNumberish, _claimedFinalState: BigNumberish, _deltas: BigNumberish[], ],
      [bigint],
      'payable'
    >
    

    
    submitChallengerMidpointClaim: TypedContractMethod<
      [_batchId: BigNumberish, _challengerStateAtMid: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    submitChallengerSingleStepClaim: TypedContractMethod<
      [_batchId: BigNumberish, _challengerClaimedPostState: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    submitSequencerMidpointClaim: TypedContractMethod<
      [_batchId: BigNumberish, _sequencerStateAtMid: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    submitSequencerSingleStepClaim: TypedContractMethod<
      [_batchId: BigNumberish, _sequencerClaimedPostState: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawClaimable: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'batches'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, bigint, bigint, boolean, boolean, boolean, boolean] & {sequencer: string, initialState: bigint, claimedFinalState: bigint, submittedAt: bigint, txCount: bigint, challenged: boolean, finalized: boolean, invalidated: boolean, bondSettled: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'bisectDispute'): TypedContractMethod<
      [_batchId: BigNumberish, _sequencerStateAtMid: BigNumberish, _challengerStateAtMid: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'challengePeriod'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'challengerBond'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'claimableBalances'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'disputes'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, boolean, boolean, bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean, boolean, bigint, bigint, boolean, boolean, boolean, boolean] & {challenger: string, active: boolean, resolved: boolean, start: bigint, end: bigint, mid: bigint, sequencerFinalState: bigint, challengerFinalState: bigint, sequencerStateAtMid: bigint, challengerStateAtMid: bigint, sequencerMidSubmitted: boolean, challengerMidSubmitted: boolean, sequencerSingleStepPostState: bigint, challengerSingleStepPostState: bigint, sequencerSingleStepSubmitted: boolean, challengerSingleStepSubmitted: boolean, sequencerWon: boolean, challengerWon: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'finalizeBatch'): TypedContractMethod<
      [_batchId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getBatchDeltas'): TypedContractMethod<
      [_batchId: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getDeltaAt'): TypedContractMethod<
      [_batchId: BigNumberish, _index: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'initiateChallenge'): TypedContractMethod<
      [_batchId: BigNumberish, _challengerFinalState: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'latestBatchId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'resolveSingleStep'): TypedContractMethod<
      [_batchId: BigNumberish, _sequencerClaimedPostState: BigNumberish, _challengerClaimedPostState: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'sequencerBond'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'submitBatch'): TypedContractMethod<
      [_initialState: BigNumberish, _claimedFinalState: BigNumberish, _deltas: BigNumberish[], ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'submitChallengerMidpointClaim'): TypedContractMethod<
      [_batchId: BigNumberish, _challengerStateAtMid: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitChallengerSingleStepClaim'): TypedContractMethod<
      [_batchId: BigNumberish, _challengerClaimedPostState: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitSequencerMidpointClaim'): TypedContractMethod<
      [_batchId: BigNumberish, _sequencerStateAtMid: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitSequencerSingleStepClaim'): TypedContractMethod<
      [_batchId: BigNumberish, _sequencerClaimedPostState: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawClaimable'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'BatchFinalized'): TypedContractEvent<BatchFinalizedEvent.InputTuple, BatchFinalizedEvent.OutputTuple, BatchFinalizedEvent.OutputObject>;
getEvent(key: 'BatchSubmitted'): TypedContractEvent<BatchSubmittedEvent.InputTuple, BatchSubmittedEvent.OutputTuple, BatchSubmittedEvent.OutputObject>;
getEvent(key: 'ChallengeInitiated'): TypedContractEvent<ChallengeInitiatedEvent.InputTuple, ChallengeInitiatedEvent.OutputTuple, ChallengeInitiatedEvent.OutputObject>;
getEvent(key: 'DisputeBisected'): TypedContractEvent<DisputeBisectedEvent.InputTuple, DisputeBisectedEvent.OutputTuple, DisputeBisectedEvent.OutputObject>;
getEvent(key: 'DisputeResolved'): TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
getEvent(key: 'MidpointClaimSubmitted'): TypedContractEvent<MidpointClaimSubmittedEvent.InputTuple, MidpointClaimSubmittedEvent.OutputTuple, MidpointClaimSubmittedEvent.OutputObject>;
getEvent(key: 'SingleStepClaimSubmitted'): TypedContractEvent<SingleStepClaimSubmittedEvent.InputTuple, SingleStepClaimSubmittedEvent.OutputTuple, SingleStepClaimSubmittedEvent.OutputObject>;

    filters: {
      
      'BatchFinalized(uint256,int256)': TypedContractEvent<BatchFinalizedEvent.InputTuple, BatchFinalizedEvent.OutputTuple, BatchFinalizedEvent.OutputObject>;
      BatchFinalized: TypedContractEvent<BatchFinalizedEvent.InputTuple, BatchFinalizedEvent.OutputTuple, BatchFinalizedEvent.OutputObject>;
    

      'BatchSubmitted(uint256,int256,int256,uint256,uint256)': TypedContractEvent<BatchSubmittedEvent.InputTuple, BatchSubmittedEvent.OutputTuple, BatchSubmittedEvent.OutputObject>;
      BatchSubmitted: TypedContractEvent<BatchSubmittedEvent.InputTuple, BatchSubmittedEvent.OutputTuple, BatchSubmittedEvent.OutputObject>;
    

      'ChallengeInitiated(uint256,int256)': TypedContractEvent<ChallengeInitiatedEvent.InputTuple, ChallengeInitiatedEvent.OutputTuple, ChallengeInitiatedEvent.OutputObject>;
      ChallengeInitiated: TypedContractEvent<ChallengeInitiatedEvent.InputTuple, ChallengeInitiatedEvent.OutputTuple, ChallengeInitiatedEvent.OutputObject>;
    

      'DisputeBisected(uint256,uint256,uint256,uint256,bool)': TypedContractEvent<DisputeBisectedEvent.InputTuple, DisputeBisectedEvent.OutputTuple, DisputeBisectedEvent.OutputObject>;
      DisputeBisected: TypedContractEvent<DisputeBisectedEvent.InputTuple, DisputeBisectedEvent.OutputTuple, DisputeBisectedEvent.OutputObject>;
    

      'DisputeResolved(uint256,bool,bool,uint256)': TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
      DisputeResolved: TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
    

      'MidpointClaimSubmitted(uint256,address,bool,uint256,int256)': TypedContractEvent<MidpointClaimSubmittedEvent.InputTuple, MidpointClaimSubmittedEvent.OutputTuple, MidpointClaimSubmittedEvent.OutputObject>;
      MidpointClaimSubmitted: TypedContractEvent<MidpointClaimSubmittedEvent.InputTuple, MidpointClaimSubmittedEvent.OutputTuple, MidpointClaimSubmittedEvent.OutputObject>;
    

      'SingleStepClaimSubmitted(uint256,address,bool,uint256,int256)': TypedContractEvent<SingleStepClaimSubmittedEvent.InputTuple, SingleStepClaimSubmittedEvent.OutputTuple, SingleStepClaimSubmittedEvent.OutputObject>;
      SingleStepClaimSubmitted: TypedContractEvent<SingleStepClaimSubmittedEvent.InputTuple, SingleStepClaimSubmittedEvent.OutputTuple, SingleStepClaimSubmittedEvent.OutputObject>;
    
    };
  }