/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface SimpleOptimisticRollupInterface extends Interface {
    getFunction(nameOrSignature: "batches" | "challengeBatch" | "challengePeriod" | "finalizeBatch" | "latestBatchId" | "submitBatch"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BatchChallenged" | "BatchFinalized" | "BatchSubmitted"): EventFragment;

    encodeFunctionData(functionFragment: 'batches', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'challengeBatch', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'challengePeriod', values?: undefined): string;
encodeFunctionData(functionFragment: 'finalizeBatch', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'latestBatchId', values?: undefined): string;
encodeFunctionData(functionFragment: 'submitBatch', values: [BytesLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'batches', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'challengeBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'challengePeriod', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalizeBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'latestBatchId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitBatch', data: BytesLike): Result;
  }

  
    export namespace BatchChallengedEvent {
      export type InputTuple = [batchId: BigNumberish, challenger: AddressLike, reasonHash: BytesLike];
      export type OutputTuple = [batchId: bigint, challenger: string, reasonHash: string];
      export interface OutputObject {batchId: bigint, challenger: string, reasonHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BatchFinalizedEvent {
      export type InputTuple = [batchId: BigNumberish, stateRoot: BytesLike];
      export type OutputTuple = [batchId: bigint, stateRoot: string];
      export interface OutputObject {batchId: bigint, stateRoot: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BatchSubmittedEvent {
      export type InputTuple = [batchId: BigNumberish, stateRoot: BytesLike, txRoot: BytesLike, submittedAt: BigNumberish];
      export type OutputTuple = [batchId: bigint, stateRoot: string, txRoot: string, submittedAt: bigint];
      export interface OutputObject {batchId: bigint, stateRoot: string, txRoot: string, submittedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SimpleOptimisticRollup extends BaseContract {
    
    connect(runner?: ContractRunner | null): SimpleOptimisticRollup;
    waitForDeployment(): Promise<this>;

    interface: SimpleOptimisticRollupInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    batches: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, boolean, boolean] & {stateRoot: string, txRoot: string, submittedAt: bigint, challenged: boolean, finalized: boolean }],
      'view'
    >
    

    
    challengeBatch: TypedContractMethod<
      [_batchId: BigNumberish, _reasonHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    challengePeriod: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    finalizeBatch: TypedContractMethod<
      [_batchId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    latestBatchId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    submitBatch: TypedContractMethod<
      [_stateRoot: BytesLike, _txRoot: BytesLike, ],
      [bigint],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'batches'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, boolean, boolean] & {stateRoot: string, txRoot: string, submittedAt: bigint, challenged: boolean, finalized: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'challengeBatch'): TypedContractMethod<
      [_batchId: BigNumberish, _reasonHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'challengePeriod'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'finalizeBatch'): TypedContractMethod<
      [_batchId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'latestBatchId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'submitBatch'): TypedContractMethod<
      [_stateRoot: BytesLike, _txRoot: BytesLike, ],
      [bigint],
      'nonpayable'
    >;

    getEvent(key: 'BatchChallenged'): TypedContractEvent<BatchChallengedEvent.InputTuple, BatchChallengedEvent.OutputTuple, BatchChallengedEvent.OutputObject>;
getEvent(key: 'BatchFinalized'): TypedContractEvent<BatchFinalizedEvent.InputTuple, BatchFinalizedEvent.OutputTuple, BatchFinalizedEvent.OutputObject>;
getEvent(key: 'BatchSubmitted'): TypedContractEvent<BatchSubmittedEvent.InputTuple, BatchSubmittedEvent.OutputTuple, BatchSubmittedEvent.OutputObject>;

    filters: {
      
      'BatchChallenged(uint256,address,bytes32)': TypedContractEvent<BatchChallengedEvent.InputTuple, BatchChallengedEvent.OutputTuple, BatchChallengedEvent.OutputObject>;
      BatchChallenged: TypedContractEvent<BatchChallengedEvent.InputTuple, BatchChallengedEvent.OutputTuple, BatchChallengedEvent.OutputObject>;
    

      'BatchFinalized(uint256,bytes32)': TypedContractEvent<BatchFinalizedEvent.InputTuple, BatchFinalizedEvent.OutputTuple, BatchFinalizedEvent.OutputObject>;
      BatchFinalized: TypedContractEvent<BatchFinalizedEvent.InputTuple, BatchFinalizedEvent.OutputTuple, BatchFinalizedEvent.OutputObject>;
    

      'BatchSubmitted(uint256,bytes32,bytes32,uint256)': TypedContractEvent<BatchSubmittedEvent.InputTuple, BatchSubmittedEvent.OutputTuple, BatchSubmittedEvent.OutputObject>;
      BatchSubmitted: TypedContractEvent<BatchSubmittedEvent.InputTuple, BatchSubmittedEvent.OutputTuple, BatchSubmittedEvent.OutputObject>;
    
    };
  }